### ISSUE TITLE
发送指令后出现红色字体报错，然后重连反向

### ISSUE THREAD

**Issue by ks-EKY** [BeiYazi0/fake_news#3]
[2024-07-08 20:10:51] [ERROR]: 处置WS命令时发生无法恢复的异常：runtime error: index out of range [0] with length 0
goroutine 383 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest.func1()
        github.com/Mrs4s/go-cqhttp/server/websocket.go:471 +0x46
panic({0x753040, 0xc0002020a8})
        runtime/panic.go:884 +0x213
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).nextAddr(0xc00018f310?)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/highway.go:227 +0xfd
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).selectConn(0x0?)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/highway.go:248 +0xe5
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).uploadSingle(0xc0000ae000, {0x1b, {0x8a3600, 0xc0003748d0}, {0xc00001a3f0, 0x10, 0x10}, 0x125, {0xc000028070, 0x68, ...}, ...})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/bdh.go:39 +0x68
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).Upload(0xc0000ae000, {0x1b, {0x8a3600, 0xc0003748d0}, {0xc00001a3f0, 0x10, 0x10}, 0x125, {0xc000028070, 0x68, ...}, ...})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/bdh.go:117 +0x425
github.com/Mrs4s/MiraiGo/client.(*ForwardMessageBuilder).Main(0xc00018f868, 0xc000088408)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/multimsg.go:316 +0x5b8
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).uploadForwardElement(0xc00020a100, {0x5, {0xc0000a4053, 0x64}, {0x0, 0x0}, 0x0, 0x53, {0x0, 0x0, ...}}, ...)
        github.com/Mrs4s/go-cqhttp/coolq/api.go:962 +0x1e5
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGroupForwardMessage(0xc00020a100, 0x0?, {0x5, {0xc0000a4053, 0x64}, {0x0, 0x0}, 0x0, 0x53, {0x0, ...}})
        github.com/Mrs4s/go-cqhttp/coolq/api.go:978 +0x7d
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).call(0xc0000fcce0, {0xc0000a400c, 0x16}, 0xc55620, {0x8a5100, 0xc0003a0230})
        github.com/Mrs4s/go-cqhttp/modules/api/api.go:38 +0x1ac5
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).Call(0xc0000fcce0, {0xc0000a400c, 0x16}, 0xc0000a4000?, {0x8a5100, 0xc0003a0230})
        github.com/Mrs4s/go-cqhttp/modules/api/caller.go:35 +0xc5
github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest(0xc000088150, 0x7f03d0?, {0xc0000a4000?, 0xc000200390?, 0xc0003a6420?})
        github.com/Mrs4s/go-cqhttp/server/websocket.go:480 +0x41c
github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI.func2(0xc0001cc300?)
        github.com/Mrs4s/go-cqhttp/server/websocket.go:325 +0x95
created by github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI
        github.com/Mrs4s/go-cqhttp/server/websocket.go:323 +0x1b2

**Comment by BeiYazi0** [comment]
有引发错误的聊天上下文截图吗
